### ISSUE TITLE
Confusing dates in Recent alerts

### ISSUE THREAD

**Issue by lmolent** [A3sal0n/FalconGate#19]
Hi,
I think that columns "First seen" and "Last seen" are confusing because of "First seen" is apparently date of alert but "Last seen" is date of last seen of device not date of last seen event which was triggered alarm.

**Comment by A3sal0n** [comment]
hi @lmolent 

Is your question related to alerts on new devices or other alerts? Could you explain better what you would like to see?

Thanks

**Comment by lmolent** [comment]
Hi. Is related to malicious activity alerts in tab "Recent alerts". Column named "First seen" is date when malicious activity was detected, that's ok, but column "Last seen" is not about last seen of this malicious activity but about last seen device activity in general, because this timestamp is updated (when I tested it) after each not-malicious traffic, what is confusig to me.

**Comment by A3sal0n** [comment]
Hi,

As you can see in the picture below, generated in our lab environment, the host with IP address ending in .106 was first reported in the network at 03:42:49. In this case the "last seen" time wasn't updated even if the host continued to be online having normal activity for few hours and launched a port scan on the gateway at 07:05:31. 

![selection_013](https://cloud.githubusercontent.com/assets/16090458/24335045/4e1b5232-1276-11e7-90be-d939f426efd4.png)

It seems that we're not able to replicate this behavior you described. Could you please provide some evidence of the issue in a screenshot as we did above? This could probably help further.

Thanks

**Comment by lmolent** [comment]
After first attempt connecting from my test host to tor exit node by command
```
# telnet 92.240.254.98 80
Trying 92.240.254.98...
telnet: connect to address 92.240.254.98: Connection refused
telnet: Unable to connect to remote host
```

alert is detected:

![screen shot 2017-03-27 at 14 10 14](https://cloud.githubusercontent.com/assets/23703392/24355892/029e53e0-12f8-11e7-8324-fe1d0e957b79.png)

That's ok, but "Last seen" column is updated regulary despite of no connection to 92.240.254.98 from my test host (checked by tcpdump).:

![screen shot 2017-03-27 at 14 25 34](https://cloud.githubusercontent.com/assets/23703392/24356197/480487dc-12f9-11e7-85b6-af3acf87ea6e.png)

**Comment by A3sal0n** [comment]
Hi,

Thanks for the screenshots. This is not a desired behavior so we will look into it asap.

**Comment by A3sal0n** [comment]
Hi,

We fixed the issue you described in our latest commit (4d8b594)

Thanks for your help!
