### ISSUE TITLE
change default ip

### ISSUE THREAD

**Issue by jeanlk15** [A3sal0n/FalconGate#29]
is it ok to change the default IP in /etc/network/interfaces as we like ? will it affect operation if we change it ? I will take it to another friends house where his provider is different

iface eth0:1 inet static
address 192.168.X.2
netmask 255.255.255.0
gateway 192.168.X.1

**Comment by A3sal0n** [comment]
This shouldn't be an issue as long as you provide the correct configuration for your friend's home gateway.

You must change the IP address also in the configuration files below:

/etc/dnsmasq.conf
/etc/nginx/sites-available/default

Then reboot your device and it should work.

**Comment by jeanlk15** [comment]
Oh Thanks Very Much Leonardo I think I will try it out , your whole package
seems to be a very well thought and put together package !
