### ISSUE TITLE
How to get web gui started

### ISSUE THREAD

**Issue by JonLittleIT** [A3sal0n/FalconGate#31]
do you have a list of steps to get the GUI working when you SSH into the pi?

**Comment by easy4MEr** [comment]
WebGUI should be automaticaly up, once installation process is finished. You can access it via http://falcongates-IP

**Comment by A3sal0n** [comment]
Usually the last octect of your FG's IP should be ".2" and the first 3 octects depend on which was the IP address which was assigned for the first time by your home router to FG. For example if your router's original DHCP was assigning IP addresses in the range 192.168.1.0/24 then your FG will be configured with the static IP 192.168.1.2 after installation.
