### ISSUE TITLE
installing on a ras pi 

### ISSUE THREAD

**Issue by JonLittleIT** [A3sal0n/FalconGate#32]
pi@raspberrypi:/opt/FalconGate $ sudo ./install.py
Detecting default gateway...
eth0 192.168.1.1
Updating apt sources...
Hit http://archive.raspberrypi.org jessie InRelease
Hit http://mirrordirector.raspbian.org jessie InRelease
Hit http://archive.raspberrypi.org jessie/main armhf Packages
Hit http://mirrordirector.raspbian.org jessie/main armhf Packages
Hit http://archive.raspberrypi.org jessie/ui armhf Packages
Hit http://mirrordirector.raspbian.org jessie/contrib armhf Packages
Hit http://mirrordirector.raspbian.org jessie/non-free armhf Packages
Hit http://mirrordirector.raspbian.org jessie/rpi armhf Packages
Ign http://archive.raspberrypi.org jessie/main Translation-en_GB
Ign http://mirrordirector.raspbian.org jessie/contrib Translation-en_GB
Ign http://archive.raspberrypi.org jessie/main Translation-en
Ign http://mirrordirector.raspbian.org jessie/contrib Translation-en
Ign http://mirrordirector.raspbian.org jessie/main Translation-en_GB
Ign http://archive.raspberrypi.org jessie/ui Translation-en_GB
Ign http://mirrordirector.raspbian.org jessie/main Translation-en
Ign http://mirrordirector.raspbian.org jessie/non-free Translation-en_GB
Ign http://archive.raspberrypi.org jessie/ui Translation-en
Ign http://mirrordirector.raspbian.org jessie/non-free Translation-en
Ign http://mirrordirector.raspbian.org jessie/rpi Translation-en_GB
Ign http://mirrordirector.raspbian.org jessie/rpi Translation-en
E: Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable)
E: Unable to lock the administration directory (/var/lib/dpkg/), is another process using it?
Installing dependencies...
E: Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable)
E: Unable to lock the administration directory (/var/lib/dpkg/), is another process using it?
Installing Bro...
Cloning Bro repo...
Cloning into 'bro'...
remote: Counting objects: 87932, done.
remote: Compressing objects: 100% (26438/26438), done.
remote: Total 87932 (delta 63845), reused 80090 (delta 57314)
Receiving objects: 100% (87932/87932), 42.65 MiB | 471.00 KiB/s, done.
fatal: Out of memory, malloc failed (tried to allocate 85876875 bytes)
fatal: index-pack failed
Traceback (most recent call last):
  File "./install.py", line 151, in <module>
    main()
  File "./install.py", line 83, in main
    os.chdir("bro")
OSError: [Errno 2] No such file or directory: 'bro'

**Comment by JonLittleIT** [comment]
its a memory error on alot.

pi@raspberrypi:/opt/FalconGate $ ./falcongate.py
Traceback (most recent call last):
  File "./falcongate.py", line 38, in <module>
    top_domains = utils.get_top_domains("top_domains.sqlite")
  File "/opt/FalconGate/lib/utils.py", line 210, in get_top_domains
    rows = cur.fetchall()
MemoryError

**Comment by A3sal0n** [comment]
The first error with message "Could not get lock /var/lib/dpkg/lock" when attempting to install in Armbian's Raspbian image it's caused by the fact that the system was designed by Armbian to get automatically updates once it's deployed to your single board computer and started for the first time. You must wait for a while after you boot it for the first time after Raspbian's installation (30min to be sure) and then start the installation of FalconGate with the correct install.py script.

The second issue may be caused by the fact that your single board device it's running low in RAM. Could you share the specifications of your device? We have never encountered this issue before in boards with 1GB of RAM or more.

**Comment by JonLittleIT** [comment]
I upgraded to avoid complications with a new pi 3. I will post status today on if it works better with new specs. The other errors was from old hardware from years ago pi 1's. Now I will use a new pi 3 with 32GB of space. I will update shortly...

**Comment by JonLittleIT** [comment]
I found some issues with the IMG file you guys posted.

![falcongate error](https://cloud.githubusercontent.com/assets/22354862/25753078/1ca0e2ae-316f-11e7-8b73-46cfef85f8e9.jpg)





the image I got some errors finding the bro directory with your image you have.

**Comment by JonLittleIT** [comment]
I think the DNS was set to the loop back.

If you dont use it as a gateway but you just want to get it online and updated can that still work or do more settings need update besides the DNS...all the update URL's in the image are not connecting but it can get on the network. I can login with console but no SSH with your image.

**Comment by A3sal0n** [comment]
Hi

If you deploy one of our pre-configured images from our wiki downloads page you don't have to reinstall FalconGate again. It's already installed and properly configured in those images.

If you are trying to install FalconGate from source to a Raspberry Pi 3 we recommend you to do the following:

1. Download and install the base Raspbian image to your SD card from the official site (https://downloads.raspberrypi.org/raspbian_lite_latest)

2. Execute the steps from our [install guide](https://github.com/A3sal0n/FalconGate/wiki/Install-from-source)

Currently the only OS image we have tested for Raspberry Pi is the official Raspbian Lite image (above) provided by the Raspberry Pi foundation. You can find the list of all the tested devices and systems [here](https://github.com/A3sal0n/FalconGate/wiki/Tested-platforms-and-devices)
