### ISSUE TITLE
Enabling DNS over HTTPS

### ISSUE THREAD

**Issue by A3sal0n** [A3sal0n/FalconGate#33]
We are working to implement DNS over HTTPS to protect against DNS spoofing all the devices connected to the FalconGate network at once and block your ISP or other parties from spying on the plain DNS requests.

**Comment by easy4MEr** [comment]
Currently testing the new feature.

**Comment by JonLittleIT** [comment]
great idea.

**Comment by A3sal0n** [comment]
Closing since the new feature seems to be working without issues.
