### ISSUE TITLE
FalconGate web app 

### ISSUE THREAD

**Issue by VinSz2** [A3sal0n/FalconGate#41]
Hello everybody,

wanted to try it out on my pine64 with armbian, but no matter what, it seems that there is no possibility to login into the web interface.

i try to reach the ip adress via browser, also i tried letting on the dhcp of the router and turn it off, which unfortunately results with no ip address designation for the pine.

regards

Vin

**Comment by A3sal0n** [comment]
Hi @VinSz2 

Are you using our preconfigured Ubuntu armbian image or you are trying to install from source?

**Comment by VinSz2** [comment]
I tried both, Downloaded the pine64 Image and also compilled it.

Both Not really working, also manually Set Up the configuration on the
devices to use it as a Gateway, turned off dhcp from the Router and so on,
still cannot Connect to tge Web App, using the 192.168.0.2 and the other
possibilities.

Regards



Am 06.09.2017 14:27 schrieb "Leonardo Mokarzel Falcon" <
notifications@github.com>:

**Comment by easy4MEr** [comment]
Hello VinSz2,

What is value your **iface** variable in /opt/FalconGate/config.ini ?
What is output of ifconfig command?

**Comment by VinSz2** [comment]
sorry for the late answer, was on vaccacion.

iface>/opt/FalconGate/config.ini
iface = eth0


eth0      Link encap:Ethernet  HWaddr 56:7c:2f:64:0f:1a
          inet addr:192.168.2.5  Bcast:192.168.2.255  Mask:255.255.255.0
          inet6 addr: fe80::547c:2fff:fe64:f1a/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:7494 errors:0 dropped:0 overruns:0 frame:0
          TX packets:3901 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:1911952 (1.9 MB)  TX bytes:1670364 (1.6 MB)
          Interrupt:114

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:271 errors:0 dropped:0 overruns:0 frame:0
          TX packets:271 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:20171 (20.1 KB)  TX bytes:20171 (20.1 KB)

tun0      Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00
          inet addr:10.8.0.1  P-t-P:10.8.0.1  Mask:255.255.255.0
          UP POINTOPOINT RUNNING NOARP MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:100
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

**Comment by easy4MEr** [comment]
Hi VinSz2,

reason why are you not able to access FalconGate's WebGui at 192.168.0.2 is that your FalcoGate has assigned different IP address. In your case it is 192.168.2.5

- Did you manually interact with your eth0 interface?

We recommend you to flash your pine64 with fresh FalconGate image once again. Once you will do that, could you please share with us once again your iface variable in /opt/FalconGate/config.ini and output of ifconfig command?

**Comment by A3sal0n** [comment]
@VinSz2 I'm closing this for now since there was no further feedback from your side.

Feel free to open a new issue if the problem persists.
