### ISSUE TITLE
homenet.pkl is gone

### ISSUE THREAD

**Issue by A3sal0n** [A3sal0n/FalconGate#43]
We decided to stop writing the pickle file homenet.pkl to disk because the write action was causing some performance issues once the homenet object in memory grew enough.

This change represents no impact in the current features and the alerts history is saved in the sqlite db under "logs/alerts.sqlite"

**Comment by easy4MEr** [comment]
After removing homenet.pkl I have observed much better performace of FalconGate in all aspetcs (Webgui, API)

**Comment by A3sal0n** [comment]
Looking good

Closing this one
