### ISSUE TITLE
Other device installation

### ISSUE THREAD

**Issue by 007scorpio** [A3sal0n/FalconGate#48]
Hi, can this be installed on other devices apart from raspberry pi series?

**Comment by A3sal0n** [comment]
Hi @007scorpio 
FalconGate can be installed also in other single board devices. We have been successful with the Banana Pi, Asus Tinkerboard and Pine64. For these devices we used the images provided by [armbian](https://www.armbian.com/). The platform can be installed as well on any device supporting Ubuntu Xenial or Debian. With some tweaking you can also get advantage of multiple Ethernet interfaces in more powerful boards with x86 or x86-64 CPUs.
