### ISSUE TITLE
lost password

### ISSUE THREAD

**Issue by jeanlk15** [A3sal0n/FalconGate#58]
is there some way to get back the lost password of the admin login ?

**Comment by easy4MEr** [comment]
Hi jeanlk15,

password to admin webpage is stored in _/opt/FalconGate/html/pwd.db_. Passwords in this .db file are hashed using default PHP function **password_hash** [(Check official documentation here)](https://secure.php.net/manual/en/function.password-hash.php)

You can try to hash your new password for example here: [http://www.passwordtool.hu/php5-password-hash-generator](http://www.passwordtool.hu/php5-password-hash-generator) and then save the generated value in the _/opt/FalconGate/html/pwd.db_

**Comment by jeanlk15** [comment]
Thanks Very Much
