### ISSUE TITLE
does url filtering work ?

### ISSUE THREAD

**Issue by jeanlk15** [A3sal0n/FalconGate#59]
shall i put info through the config.ini or use the web gui ? i tried to block for example yahoo.com but did not seem to work

what way one can do this ?

**Comment by A3sal0n** [comment]
You can block arbitrary domains and IP addresses in the "Configuration" page using the input text field "Blacklist".  You can also add multiple mixed IPs and domains separated by commas. See the example below.

![image](https://user-images.githubusercontent.com/16090458/39721766-d1150506-5240-11e8-9eac-e4712454030d.png)

**Comment by jeanlk15** [comment]
I can't open the link something i can do to see it ?
