### ISSUE TITLE
block or alert

### ISSUE THREAD

**Issue by jeanlk15** [A3sal0n/FalconGate#61]
i wanted to clarify something 

does falcongate block or just alert ?

does it block and may not show it is blocking something ? or does it alert and block ?

**Comment by A3sal0n** [comment]
Currently Falcongate proactively blocks just domains from our threat intel feed, not IP addresses. It generates alerts when traffic is detected to both domains and IPs.

**Comment by jeanlk15** [comment]
Great thanks for clarifying
